package com.shuddhatype.engine

/**
 * Rule tables, generated from the verified JavaScript engine. Do not retype
 * these by hand — regenerate if the JS reference changes.
 *
 * Order matters in CONS/MATRA/INDEP: matching is longest-first, so "chh" must
 * come before "ch" and "sh" before "s". Sorting these lists alphabetically
 * breaks the engine silently.
 */
object Tables {

    val CONS: List<Pair<String, String>> = listOf(
        "chh" to "छ",
        "ksh" to "क्ष",
        "shr" to "श्र",
        "kh" to "ख",
        "gh" to "घ",
        "ng" to "ङ",
        "ch" to "च",
        "jh" to "झ",
        "th" to "थ",
        "dh" to "ध",
        "ph" to "फ",
        "bh" to "भ",
        "sh" to "श",
        "gy" to "ज्ञ",
        "jn" to "ज्ञ",
        "k" to "क",
        "g" to "ग",
        "c" to "च",
        "j" to "ज",
        "t" to "त",
        "d" to "द",
        "n" to "न",
        "p" to "प",
        "f" to "फ",
        "b" to "ब",
        "m" to "म",
        "y" to "य",
        "r" to "र",
        "l" to "ल",
        "v" to "व",
        "w" to "व",
        "s" to "स",
        "h" to "ह",
        "x" to "छ",
        "z" to "ज",
        "q" to "क"
    )

    val MATRA: List<Pair<String, String>> = listOf(
        "aa" to "ा",
        "ai" to "ै",
        "au" to "ौ",
        "ou" to "ौ",
        "ee" to "ी",
        "ii" to "ी",
        "oo" to "ू",
        "uu" to "ू",
        "a" to "",
        "i" to "ि",
        "u" to "ु",
        "e" to "े",
        "o" to "ो"
    )

    val INDEP: List<Pair<String, String>> = listOf(
        "aa" to "आ",
        "ai" to "ऐ",
        "au" to "औ",
        "ou" to "औ",
        "ee" to "ई",
        "ii" to "ई",
        "oo" to "ऊ",
        "uu" to "ऊ",
        "a" to "अ",
        "i" to "इ",
        "u" to "उ",
        "e" to "ए",
        "o" to "ओ"
    )

    val DIGITS: Map<Char, String> = mapOf(
        '0' to "०", '1' to "१", '2' to "२", '3' to "३", '4' to "४",
        '5' to "५", '6' to "६", '7' to "७", '8' to "८", '9' to "९"
    )

    /** Spellings Nepali writers genuinely confuse. This is the शुद्धि core. */
    val CONS_ALT: Map<String, List<String>> = mapOf(
        "स" to listOf("श", "ष"),
        "श" to listOf("स", "ष"),
        "ष" to listOf("स", "श"),
        "ब" to listOf("व", "भ"),
        "व" to listOf("ब", "भ"),
        "भ" to listOf("व", "ब"),
        "त" to listOf("ट"),
        "ट" to listOf("त"),
        "थ" to listOf("ठ"),
        "ठ" to listOf("थ"),
        "द" to listOf("ड"),
        "ड" to listOf("द"),
        "ध" to listOf("ढ"),
        "ढ" to listOf("ध"),
        "न" to listOf("ण"),
        "ण" to listOf("न"),
        "क" to listOf("ख"),
        "ग" to listOf("घ"),
        "ज" to listOf("झ"),
        "ज्ञ" to listOf("ज्न"),
        "च" to listOf("छ"),
        "छ" to listOf("च")
    )

    val MATRA_ALT: Map<String, List<String>> = mapOf(
        "" to listOf("ा", "ँ"),
        "ा" to listOf("ाँ"),
        "ि" to listOf("ी"),
        "ी" to listOf("ि"),
        "ु" to listOf("ू"),
        "ू" to listOf("ु"),
        "े" to listOf("ें", "ेँ"),
        "ो" to listOf("ों", "ोँ"),
        "ै" to listOf("ैं", "ैँ"),
        "ौ" to listOf("ौँ", "ौं", "ाउ", "ाउँ")
    )

    /**
     * Chat shorthand. Pure convention with no phonetic basis, so it is matched
     * as a whole token before any rule runs — otherwise "k" becomes खा.
     */
    val SHORT: Map<String, String> = mapOf(
        "k" to "के",
        "kk" to "के के",
        "ke" to "के",
        "x" to "छ",
        "xa" to "छ",
        "xu" to "छु",
        "xas" to "छस्",
        "xan" to "छन्",
        "xau" to "छौ",
        "xaun" to "छौं",
        "xaina" to "छैन",
        "xainan" to "छैनन्",
        "xin" to "छिन्",
        "xa2" to "छ",
        "garx" to "गर्छ",
        "garxu" to "गर्छु",
        "garxan" to "गर्छन्",
        "grx" to "गर्छ",
        "grxu" to "गर्छु",
        "hunx" to "हुन्छ",
        "hunxa" to "हुन्छ",
        "janx" to "जान्छ",
        "janxu" to "जान्छु",
        "vanx" to "भन्छ",
        "vanxu" to "भन्छु",
        "dinx" to "दिन्छ",
        "aunx" to "आउँछ",
        "vayo" to "भयो",
        "vane" to "भने",
        "vanne" to "भन्ने",
        "vaneko" to "भनेको",
        "vai" to "भाइ",
        "vet" to "भेट",
        "vetnu" to "भेट्नु",
        "vanchu" to "भन्छु",
        "vari" to "भरि",
        "vok" to "भोक",
        "gr" to "गर",
        "mlai" to "मलाई",
        "tmi" to "तिमी",
        "tmro" to "तिम्रो",
        "tpai" to "तपाईं",
        "tpailai" to "तपाईंलाई",
        "hjr" to "हजुर",
        "kso" to "कस्तो",
        "kaso" to "कस्तो",
        "knai" to "कुनै",
        "aile" to "अहिले",
        "aba" to "अब",
        "vk" to "भक",
        "t" to "त",
        "l" to "ल",
        "n" to "न",
        "m" to "म",
        "r" to "र",
        "ni" to "नि",
        "ta" to "त",
        "la" to "ल"
    )

    /** Postpositions and the plural हरू attach to the previous word. */
    val POSTPOS: Map<String, String> = mapOf(
        "ma" to "मा",
        "mai" to "मै",
        "le" to "ले",
        "ko" to "को",
        "ka" to "का",
        "ki" to "की",
        "lai" to "लाई",
        "bata" to "बाट",
        "sanga" to "सँग",
        "haru" to "हरू",
        "harу" to "हरू",
        "haroo" to "हरू",
        "samma" to "सम्म",
        "dekhi" to "देखि",
        "kai" to "कै",
        "sita" to "सित"
    )

    /** Hand-tuned romanisations of the most common words. */
    val DICT: Map<String, String> = mapOf(
        "cha" to "छ|च",
        "chha" to "छ",
        "chan" to "छन्",
        "chhan" to "छन्",
        "chu" to "छु",
        "chhu" to "छु",
        "chau" to "छौ",
        "chaun" to "छौं",
        "chhau" to "छौ",
        "chaina" to "छैन",
        "chhaina" to "छैन",
        "chainan" to "छैनन्",
        "ho" to "हो",
        "hoina" to "होइन",
        "hoinan" to "होइनन्",
        "hun" to "हुन्",
        "huncha" to "हुन्छ",
        "hunchha" to "हुन्छ",
        "hudaina" to "हुँदैन",
        "hunuhuncha" to "हुनुहुन्छ",
        "hunuhunchha" to "हुनुहुन्छ",
        "hunuhunna" to "हुनुहुन्न",
        "thiyo" to "थियो",
        "thiena" to "थिएन",
        "thie" to "थिए",
        "bhayo" to "भयो",
        "bhaena" to "भएन",
        "bhaeko" to "भएको",
        "bhane" to "भने",
        "garchu" to "गर्छु",
        "garchhu" to "गर्छु",
        "garcha" to "गर्छ",
        "garchha" to "गर्छ",
        "garyo" to "गर्‍यो",
        "gare" to "गरे",
        "gareko" to "गरेको",
        "garne" to "गर्ने",
        "garnu" to "गर्नु",
        "gara" to "गर",
        "garau" to "गरौँ|गरौं",
        "jancha" to "जान्छ",
        "janchu" to "जान्छु",
        "gayo" to "गयो",
        "jau" to "जाऊ",
        "janu" to "जानु",
        "aayo" to "आयो",
        "ayo" to "आयो",
        "aaucha" to "आउँछ",
        "khana" to "खाना",
        "khanu" to "खानु",
        "khayo" to "खायो",
        "khau" to "खाऊ",
        "diyo" to "दियो",
        "dinu" to "दिनु",
        "liyo" to "लियो",
        "linu" to "लिनु",
        "herna" to "हेर्न",
        "hernu" to "हेर्नु",
        "sunnu" to "सुन्नु",
        "bolnu" to "बोल्नु",
        "lekhnu" to "लेख्नु",
        "padhnu" to "पढ्नु",
        "basnu" to "बस्नु",
        "uthnu" to "उठ्नु",
        "saknu" to "सक्नु",
        "parcha" to "पर्छ",
        "paryo" to "पर्‍यो",
        "lagcha" to "लाग्छ",
        "lagyo" to "लाग्यो",
        "milcha" to "मिल्छ",
        "chahincha" to "चाहिन्छ",
        "bhancha" to "भन्छ",
        "bhanyo" to "भन्यो",
        "bhanne" to "भन्ने",
        "sochcha" to "सोच्छ",
        "dinchu" to "दिन्छु",
        "lagyo " to "लाग्यो",
        "napar" to "नपर",
        "mausam" to "मौसम",
        "baschu" to "बस्छु",
        "baschhu" to "बस्छु",
        "lyayo" to "ल्यायो",
        "mahattwa" to "महत्त्व",
        "mahatwa" to "महत्त्व",
        "suru" to "सुरु",
        "siksha" to "शिक्षा",
        "pariksha" to "परीक्षा",
        "parikshya" to "परीक्षा",
        "aspatal" to "अस्पताल",
        "biswabidyalaya" to "विश्वविद्यालय",
        "biswabidhyalaya" to "विश्वविद्यालय",
        "sarkarle" to "सरकारले",
        "sundar" to "सुन्दर",
        "desh" to "देश",
        "samadhan" to "समाधान",
        "sambidhan" to "संविधान",
        "samvidhan" to "संविधान",
        "jari" to "जारी",
        "hilo" to "हिलो",
        "college" to "कलेज",
        "padhcha" to "पढ्छ",
        "khojnuparcha" to "खोज्नुपर्छ",
        "gaen" to "गएँ",
        "khaera" to "खाएर",
        "parekole" to "परेकोले",
        "ma" to "म|मा",
        "malai" to "मलाई",
        "mero" to "मेरो",
        "hami" to "हामी",
        "hamro" to "हाम्रो",
        "hamilai" to "हामीलाई",
        "timi" to "तिमी",
        "timilai" to "तिमीलाई",
        "timro" to "तिम्रो",
        "tapai" to "तपाईं",
        "tapain" to "तपाईं",
        "tapailai" to "तपाईंलाई",
        "tapaiko" to "तपाईंको",
        "u" to "उ",
        "uni" to "उनी",
        "unko" to "उनको",
        "usko" to "उसको",
        "unle" to "उनले",
        "yo" to "यो",
        "tyo" to "त्यो",
        "yi" to "यी",
        "ti" to "ती",
        "yesto" to "यस्तो",
        "tyasto" to "त्यस्तो",
        "yeslai" to "यसलाई",
        "tyaslai" to "त्यसलाई",
        "aafno" to "आफ्नो",
        "aafai" to "आफैं",
        "ke" to "के",
        "ko" to "को",
        "kaha" to "कहाँ",
        "kahile" to "कहिले",
        "kina" to "किन",
        "kasari" to "कसरी",
        "kati" to "कति",
        "kun" to "कुन",
        "kasto" to "कस्तो",
        "kasle" to "कसले",
        "jo" to "जो",
        "jun" to "जुन",
        "jaba" to "जब",
        "taba" to "तब",
        "namaste" to "नमस्ते",
        "namaskar" to "नमस्कार",
        "dhanyabad" to "धन्यवाद",
        "dhanyavad" to "धन्यवाद",
        "dhanyawad" to "धन्यवाद",
        "swagat" to "स्वागत",
        "bida" to "बिदा",
        "maph" to "माफ",
        "sorry" to "सरी",
        "hajur" to "हजुर",
        "la" to "ल",
        "hai" to "है",
        "ni" to "नि",
        "yar" to "यार",
        "thik" to "ठीक",
        "thikai" to "ठीकै",
        "sanchai" to "सञ्चै",
        "sancho" to "सन्चो",
        "nam" to "नाम",
        "naam" to "नाम",
        "manche" to "मान्छे",
        "keta" to "केटा",
        "keti" to "केटी",
        "buba" to "बुबा",
        "ama" to "आमा",
        "dai" to "दाइ",
        "bhai" to "भाइ",
        "didi" to "दिदी",
        "bahini" to "बहिनी",
        "sathi" to "साथी",
        "pariwar" to "परिवार",
        "paribar" to "परिवार",
        "shrimati" to "श्रीमती",
        "shriman" to "श्रीमान्",
        "chhora" to "छोरा",
        "chhori" to "छोरी",
        "chora" to "छोरा",
        "chori" to "छोरी",
        "hajurba" to "हजुरबा",
        "hajurama" to "हजुरआमा",
        "nepal" to "नेपाल",
        "kathmandu" to "काठमाडौं",
        "pokhara" to "पोखरा",
        "chitwan" to "चितवन",
        "biratnagar" to "विराटनगर",
        "lalitpur" to "ललितपुर",
        "bhaktapur" to "भक्तपुर",
        "birgunj" to "वीरगन्ज",
        "dharan" to "धरान",
        "butwal" to "बुटवल",
        "himal" to "हिमाल",
        "pahad" to "पहाड",
        "terai" to "तराई",
        "gaun" to "गाउँ",
        "sahar" to "सहर",
        "ghar" to "घर",
        "bato" to "बाटो",
        "bazar" to "बजार",
        "bajar" to "बजार",
        "pasal" to "पसल",
        "karyalaya" to "कार्यालय",
        "school" to "स्कूल",
        "vidyalaya" to "विद्यालय",
        "bidyalaya" to "विद्यालय",
        "mandir" to "मन्दिर",
        "kotha" to "कोठा",
        "kitab" to "किताब",
        "kalam" to "कलम",
        "kagaj" to "कागज",
        "pani" to "पानी|पनि",
        "bhat" to "भात",
        "dal" to "दाल",
        "tarkari" to "तरकारी",
        "chiya" to "चिया",
        "dudh" to "दूध",
        "chini" to "चिनी",
        "nun" to "नुन",
        "phal" to "फल",
        "sabji" to "सब्जी",
        "masu" to "मासु",
        "paisa" to "पैसा",
        "mobile" to "मोबाइल",
        "computer" to "कम्प्युटर",
        "photo" to "फोटो",
        "gadi" to "गाडी",
        "batti" to "बत्ती",
        "dhoka" to "ढोका",
        "jhyal" to "झ्याल",
        "samaya" to "समय",
        "din" to "दिन",
        "rat" to "रात",
        "bihana" to "बिहान",
        "beluka" to "बेलुका",
        "sanjh" to "साँझ",
        "hapta" to "हप्ता",
        "mahina" to "महिना",
        "barsa" to "वर्ष",
        "barsha" to "वर्ष",
        "aaja" to "आज",
        "aja" to "आज",
        "bholi" to "भोलि",
        "hijo" to "हिजो",
        "ahile" to "अहिले",
        "pachi" to "पछि",
        "aghi" to "अघि",
        "sadhai" to "सधैं",
        "kahilekahi" to "कहिलेकाहीं",
        "ramro" to "राम्रो",
        "naramro" to "नराम्रो",
        "thulo" to "ठूलो",
        "sano" to "सानो",
        "naya" to "नयाँ",
        "purano" to "पुरानो",
        "dherai" to "धेरै",
        "thorai" to "थोरै",
        "sabai" to "सबै",
        "kehi" to "केही",
        "aru" to "अरु",
        "mitho" to "मीठो",
        "tito" to "तीतो",
        "sajilo" to "सजिलो",
        "garho" to "गाह्रो",
        "chado" to "चाँडो",
        "dhilo" to "ढिलो",
        "sacho" to "साँचो",
        "jhuto" to "झूटो",
        "sasto" to "सस्तो",
        "mahango" to "महँगो",
        "kam" to "काम",
        "kura" to "कुरा",
        "man" to "मन",
        "maya" to "माया",
        "khusi" to "खुसी",
        "dukha" to "दुःख",
        "samachar" to "समाचार",
        "sarkar" to "सरकार",
        "shiksha" to "शिक्षा",
        "sikshak" to "शिक्षक",
        "shikshak" to "शिक्षक",
        "bidyarthi" to "विद्यार्थी",
        "vidyarthi" to "विद्यार्थी",
        "doctor" to "डाक्टर",
        "bhasha" to "भाषा",
        "sanskriti" to "संस्कृति",
        "itihas" to "इतिहास",
        "prem" to "प्रेम",
        "jindagi" to "जिन्दगी",
        "jiwan" to "जीवन",
        "sapana" to "सपना",
        "bichar" to "विचार",
        "vichar" to "विचार",
        "sahayog" to "सहयोग",
        "samasya" to "समस्या",
        "upaya" to "उपाय",
        "sabda" to "शब्द",
        "shabda" to "शब्द",
        "suddha" to "शुद्ध",
        "shuddha" to "शुद्ध",
        "galat" to "गलत",
        "sahi" to "सही",
        "ra" to "र",
        "tara" to "तर",
        "ani" to "अनि",
        "pani2" to "पनि",
        "ta" to "त",
        "ki" to "कि",
        "wa" to "वा",
        "jasto" to "जस्तो",
        "jastai" to "जस्तै",
        "bata" to "बाट",
        "lai" to "लाई",
        "ma2" to "मा",
        "le" to "ले",
        "sanga" to "सँग",
        "samma" to "सम्म",
        "dekhi" to "देखि",
        "bhitra" to "भित्र",
        "bahira" to "बाहिर",
        "mathi" to "माथि",
        "tala" to "तल",
        "agadi" to "अगाडि",
        "pachadi" to "पछाडि",
        "wari" to "वारि",
        "pari" to "पारि",
        "haina" to "हैन",
        "ek" to "एक",
        "dui" to "दुई",
        "tin" to "तीन",
        "char" to "चार",
        "panch" to "पाँच",
        "sat" to "सात",
        "aath" to "आठ",
        "nau" to "नौ",
        "das" to "दश"
    )
}
